Change terraform module to bring it to standard as per skeleton module.
nexient-llc/tf-azurerm-module-resource_group pull request #11
Opened 2023-10-31 16:20 UTC by nexient-ajoshi

2023-10-31 16:28 UTC, chris-taylor-ntt commented on .pre-commit-config.yaml
Looks like this was in the same `git add` as your .gitignore file. You'll want to remove this file.

2023-10-31 16:30 UTC, chris-taylor-ntt commented on NOTICE
> +Copyright 2023 Launch LLC
Is Launch LLC a legal entity? If not, we probably need to revise this to reflect the proper entity name or just remove this line entirely.

2023-10-31 16:48 UTC, chris-taylor-ntt submitted a review, later dismissed

2023-10-31 17:43 UTC, dsahoo-nexient commented on versions.tf
> +      version = "=3.77.0"
should be >=

2023-10-31 17:47 UTC, dsahoo-nexient commented on examples/complete/main.tf
> +  name       = module.resource_names["resource_group"].recommended_per_length_restriction
In the examples, it will be better not to use the resouce_name module to name the resource. instead use the random provider to generate a name like `test-<random_number>`. The whole point is these examples are supposed to be triggerred from terratest. and if we have hard-coded names, there are changes to naming conflicts when the terratests are run from the pipeline.

2023-11-01 16:20 UTC, nexient-ajoshi commented on examples/complete/main.tf
> +  name       = module.resource_names["resource_group"].recommended_per_length_restriction
fixed @dsahoo-nexient

2023-11-01 16:39 UTC, dsahoo-nexient approved these changes

2023-11-01 16:56 UTC, chris-taylor-ntt submitted a review, later dismissed

2023-11-01 17:26 UTC, bignastybryce requested changes
It's a nitpick, but you have a repeated word in the NOTICE.  You should just be able to commit my suggestion.

2023-11-01 17:26 UTC, bignastybryce commented on NOTICE
> +If you discover a file that does not specify specify its license that should be licensed, please contact the repository owners as soon as possible to resolve the issue.
```suggestion
If you discover a file that does not specify its license that should be licensed, please contact the repository owners as soon as possible to resolve the issue.
```

2023-11-01 18:09 UTC, chris-taylor-ntt approved these changes

2023-11-02 13:15 UTC, dsahoo-nexient approved these changes

2023-11-02 16:20 UTC, merged